name: BlockCondense
main: com.gmail.snowmanam2.blockcondense.BlockCondense
version: 0.0.1
author: snowman_am2
commands:
  condense:
    description: Condense ingots into blocks
    usage: /condense
    permission: blockcondense.condense
    permission-message: You don't have permission to do that.
  gold:
    description: Turn nuggets into ingots
    usage: /gold
    permission: blockcondense.gold
    permission-message: You don't have permission to do that.
  gunpowder:
    description: Turn gunpowder into TNT
    usage: /gunpowder
    aliases: [gp]
    permission: blockcondense.gunpowder
    permission-message: You don't have permission to do that.