name: BlockCondense
main: com.gmail.snowmanam2.blockcondense.BlockCondense
version: 0.0.1
author: snowman_am2
depend: [Essentials]
commands:
  blockcondense:
    description: Autocrafts from a set of ingredients
    usage: |
           /<command> <recipe> - crafts according to <recipe>
           /<command> list - lists the available recipes
           /<command> reload - reload the recipe list
    aliases: [bc]
    permission: blockcondense.blockcondense
permissions:
  blockcondense.blockcondense:
    description: Access /blockcondense
    default: true
  blockcondense.reload:
    description: Reload the recipe list
    default: op
